%YAML 1.2
---
$schema: "http://json-schema.org/draft-04/schema"
id: "/schemas/cmds"
title: yaml schemas for yaml command entries
description: |
  A yaml schema to validate command entries given in yaml format.
  Original incentive was (is so far) to run shell install commands that are read from yaml documents.
  Needed for dotfiles install.
type: object
properties:
  command_entries:
    type: array
    items:
      $ref: '#/command_entry'
    minItems: 1
additionalProperties: false
command_entry:
  type: object
  properties:
    name:
      type: string
    command:
      type: string
    description:
      type: string
    pkgs:
      $ref: '#/pkgs'
  required:
    - name
    - command
    - description
    - pkgs
  additionalProperties: false
pkgs:
  type: array
  items: string
... 
