---
command_entries: # by default install-entries should have is-sudo set to true
  - name: apt
    description: install via debian Advanced Package Tool
    command: apt install
    pkgs:
      - emacs
...
