---
note: install with debian like apt tool
install-entries: # by default install-entries should have is-sudo set to true
  apt:
    description: install via debian Advanced Package Tool
    command: apt install
    pkgs:
      - git
      - tree
      - curl  # likely already installed, but do it anyway
      - screen  # GNU screen, multiplexer
      - g++
      - python
      - yq # yaml format validator and yaml file browsing, filtering, selection
      - yamllint  # yaml file linter, schema validator, sets much stricter standard than yq
      - ccze  # log files coloriser
      - wget
  dpkg:
    command: ""
    pkgs:
      - ""
todo:
  - java jdk (basic one: default-jre), valgrind
...
