---
note: install with debian like apt tool
command: sudo apt install
  pkgs: 
    - git
    - tree
    - curl
    - screen
      description: GNU screen, multiplexer
    - g++
    - python
    - ccze
      description: log files coloriser
    - wget
todo:
  - java jdk (basic one: default-jre), valgrind
...
