---
note: install with debian like apt tool
apt:
  command: sudo apt install
  pkgs:
    - git
    - tree
    - curl  # likely already installed, but do it anyway
    - screen  # GNU screen, multiplexer
    - g++
    - python
    - yamllint  # yaml file linter
    - ccze  # log files coloriser
    - wget
dpkg:
  command: ""
  pkgs:
    - ""
todo:
  - java jdk (basic one: default-jre), valgrind
...
