# Set path if required
#export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH

# allow auto cd
setopt auto_cd

# Do not enter command lines into the history list if they are duplicates of the
# previous event.
setopt histignorealldups
setopt sharehistory

# Aliases
alias ls='ls --color=auto'
alias ll='ls -lah --color=auto'
alias grep='grep --color=auto'
alias ec="$EDITOR $HOME/.zshrc" # edit .zshrc
alias sc="source $HOME/.zshrc"  # reload zsh configuration

## Set up the prompt - if you load Theme with zplugin as in this example, this will be overriden by the Theme. If you comment out the Theme in zplugins, this will be loaded.
#autoload -Uz promptinit
#promptinit
## prompt adam1            # see Zsh Prompt Theme below
## Use modern completion system
#autoload -Uz compinit
#compinit

## Use emacs keybindings even if our EDITOR is set to vi
#bindkey -e
# moving gradually to vi keybinding
bindkey -v
bindkey "^[[5~" history-beginning-search-backward
bindkey "^[[6~" history-beginning-search-forward
bindkey "^[[1;5D" backward-word # Ctrl-left
bindkey "^[[1;5C" forward-word  # Ctrl-right
bindkey "^[[1;3D" backward-word # Alt-left
bindkey "^[[1;3C" forward-word  # Alt-right
bindkey "^[#" pound-insert  # to comment current command
# allow using hash symbol as the symbol to comment current command
bindkey "^[#" pound-insert

# Keep 5000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=5000
SAVEHIST=5000
HISTFILE=~/.zsh_history

# plugins needed 
#plugins=(git history colored-man-pages docker docker-compose emacs iterm2 node npm brew pip colorize macos pyenv colorize adb aws)

## Shell Integration and plugins
#source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
#source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
#source ~/.zsh/zsh-autocomplete/zsh-autocomplete.plugin.zsh

### Fix for Slow zsh-autosuggestions copy&paste
#autoload -Uz bracketed-paste-magic
#zle -N bracketed-paste bracketed-paste-magic
#zstyle ':bracketed-paste-magic' active-widgets '.self-*'

##BEGIN - GENERATED CONTENT, DO NOT EDIT !!!
#  [ "$COMMON_ENV_DEBUG" = "1" ] && echo "Sourcing '$0' ..." >&2
#  source "/home/myfirstdebianpc/Documents/repos/common_env/tools/shell/source/shellrc.sh"
##END - GENERATED CONTENT, DO NOT EDIT !!!

source ./.zshrc_user
source ./.aliases.zsh

# Antigen
source /usr/share/zsh-antigen/antigen.zsh
# Load Antigen configurations
antigen init ./.antigenrc
