---
command_entries: # by default install-entries should have is-sudo set to true
  - name: apt
    description: install via debian Advanced Package Tool
    command: apt install
    pkgs:
      - bats # for unit testing
      - g++
      - clang
      - valgrind
      - git
      - tree
      - curl  # likely already installed, but do it anyway
      - wget
      - screen  # GNU screen, multiplexer
      - python3
      - yq # yaml format validator, also yaml browsing, filtering, selection, etc. (for yaml schema validator, see pajv in npm install)
      - nodejs npm # nodejs: server side JS runtime environment; npm: node package manager
      - ccze  # log files coloriser
      - stow
      - zsh
      - zsh-antigen # dropped zplug for antigen
  - name: dpkg
    description: debian package manager
    command: dpkg -i
    pkgs:
      - dummypkg
...
