---
command_entries: # by default install-entries should have is-sudo set to true
  - name: apt
    description: install via debian Advanced Package Tool
    command: apt install
    command_for_test: apt list --installed
    pkgs:
      - bats # for unit testing dotfiles installation
      - g++
      - clang
      - valgrind
      - git
      - tree
      - curl  # likely already installed, but do it anyway
      - wget
      - screen  # GNU screen, multiplexer
      - python3
      - yq # yaml format validator, also yaml browsing, filtering, selection, etc. (for yaml validation against schema, see node tool 'pajv' in npm install)
      - nodejs npm # nodejs: server side JS runtime environment; npm: node package manager
      - ccze  # log files coloriser
      - stow  # needed to symlink generated dotfile folder
      - zsh
      - zsh-antigen # zsh plugins manager (dropped zplug)
  - name: dpkg
    description: debian package manager
    command: dpkg -i
    pkgs:
      - dummypkg
...
